### ISSUE TITLE
Can created fluid interactions set weights？

### ISSUE THREAD

**Issue by xinyihl** [tttsaurus/Fluid-Interaction-Tweaker#1]
like Liquid Starlight and Lava can 1/500 create Aquamarine Shale

**Comment by tttsaurus** [comment]
you mean Aquamarine Shale is a variant output?

you can basically add this feature using the event system in crt

**Comment by tttsaurus** [comment]
check out this page please
https://github.com/tttsaurus/Fluid-Interaction-Tweaker/wiki/Events

btw, event cancellation is currently unavailable on v1.2.0. ill publish the v1.2.1 with the cancellable event soon

**Comment by xinyihl** [comment]
Okay, I'll give it a try. - Thanks.
