### ISSUE TITLE
Entity conversion broken in 1.5.0

### ISSUE THREAD

**Issue by ivanbaranov23** [tttsaurus/Fluid-Interaction-Tweaker#11]
code:
![image](https://github.com/user-attachments/assets/37f01c8f-0bb5-4566-8bcd-38649187512d)
result:
![image](https://github.com/user-attachments/assets/63d0096c-b23b-4348-80a4-b277560ec65a)

code:
![image](https://github.com/user-attachments/assets/718dc86a-f0f8-4a38-90fa-4d219331b3ab)
jei result
![image](https://github.com/user-attachments/assets/483a3f71-a43b-40c0-8c92-ce005d781097)
![image](https://github.com/user-attachments/assets/97d8eef9-c7f9-4ba9-9a0c-784d5640c0d3)

**Comment by ivanbaranov23** [comment]
code as text, needs atum mod
FBTweaker.addRecipe(<liquid:sand>, FBTweaker.outputBuilder()
    
    .addEvent(FBTweaker.eventBuilder().createEntityConversionEvent(
        <entity:minecraft:zombie>, <entity:atum:mummy>
    ).addCondition(Condition.byChance, [0.1f]))
    .addEvent(FBTweaker.eventBuilder().createEntityConversionEvent(
        <entity:minecraft:zombie>, <entity:atum:wraith>
    ).addCondition(Condition.byChance, [0.1f]))
    .addEvent(FBTweaker.eventBuilder().createEntityConversionEvent(
        <entity:minecraft:zombie>, <entity:atum:forsaken>
    ).addCondition(Condition.byChance, [0.1f]))
    .addEvent(FBTweaker.eventBuilder().createEntityConversionEvent(
        <entity:minecraft:zombie>, <entity:minecraft:husk>
    ).addCondition(Condition.byChance, [0.1f]))
  
);

**Comment by ivanbaranov23** [comment]
and BoP for quicksand

**Comment by ivanbaranov23** [comment]
vanilla fluids with vanilla mobs also doesn't work

**Comment by tttsaurus** [comment]
fixed on my end, pls try the latest action build

**Comment by ivanbaranov23** [comment]
How do you do that? I am a bit of a GitHub noob

**Comment by tttsaurus** [comment]
- Go to [GitHub Actions](https://github.com/tttsaurus/Fluid-Interaction-Tweaker/actions)
- Click on the latest workflow
- Scroll down to the bottom and download the `Artifacts`
- Unzip and `fluidintetweaker-1.5.0.jar` is the mod file

**Comment by ivanbaranov23** [comment]
It works, thx
