### ISSUE TITLE
[Feature]Abiility to remove Thermal Foundation's default recipes

### ISSUE THREAD

**Issue by ghost** [tttsaurus/Fluid-Interaction-Tweaker#12]
I didn't find a way to delete recipes in the wiki page, if there is one, please let me know.
For example,block of mana infused metal.

**Comment by tttsaurus** [comment]
if you were referring to hiding jei recipes, then you can turn that off in the config. otherwise, currently theres no way to really remove thermal foundation's recipes

**Comment by ghost** [comment]
No, I want to remove them and add new ways to get them in my modpack.

**Comment by tttsaurus** [comment]
not gonna add that feature into this mod, cuz its mixin based

but i might add that into https://github.com/tttsaurus/OME-Tweaks

**Comment by ghost** [comment]
> not gonna add that feature into this mod, cuz its mixin based
> 
> but i might add that into https://github.com/tttsaurus/OME-Tweaks

That's great,will this mod be released on Curseforge later?

**Comment by mczph** [comment]
> not gonna add that feature into this mod, cuz its mixin based
> 
> but i might add that into https://github.com/tttsaurus/OME-Tweaks
That's great,will this mod be released on Curseforge later?

**Comment by tttsaurus** [comment]
yeah, currently under review

**Comment by tttsaurus** [comment]
got it done in that repo
