### ISSUE TITLE
[Feature Request] Add `Fluid+Block` and `Fluid+Entity` events

### ISSUE THREAD

**Issue by Krutoy242** [tttsaurus/Fluid-Interaction-Tweaker#5]
I believe, this features perfectly align with mod name "Fluid Interaction Tweaker" 😀

I like this features in other mods, like ExNihilo Witch Water that turns one mobs into others. Or ThermalExpansion fluids like Pyrotheum that melting blocks when flowing. It would be cool if this interactions could be tweaked with your mod!

![image](https://github.com/user-attachments/assets/494fe987-0e5a-405a-85ff-74518b7f04ae)

https://github.com/user-attachments/assets/0dc6c483-300e-4093-ab6a-337bb70d0811

**Comment by tttsaurus** [comment]
ill try, but still the same sentence
"im not sure how long it takes me to finish since currently busy with other things"

especially for the second feature, the fluid turns the surrounding blocks into sth
currently, the mod only allows the fluid to turn into sth instead of changing its surrounding

From wiki
![image](https://github.com/user-attachments/assets/4ebd8779-7238-4e88-a993-8f3669386440)

i dont know whether you noticed that
im only allowing fluid to be the `initiator` since it's flowing and notifying other things
and blocks are never the `initiator` which means they never turn to sth else

i think you can just add the second feature by listening to the event
it's quite conflicting with my design and code written

**Comment by tttsaurus** [comment]
second feature implemented by crt

![image](https://github.com/user-attachments/assets/119c89fc-04eb-4e44-8346-3c71b9a2b62a)

```
#reloadable

import mods.fluidintetweaker.FITweaker;
import mods.fluidintetweaker.event.CustomFluidInteractionEvent;
import mods.zenutils.EventPriority;
import crafttweaker.world.IFacing;

var recipes as [string] = FITweaker.addRecipe(<liquid:cobalt>, false, <item:minecraft:gold_block>.asBlock(), <item:minecraft:diamond_block>.asBlock());

events.register(function(event as CustomFluidInteractionEvent)
{
    var thisRecipe = event.liquidInteractionRecipeKey;

    for recipe in recipes
    {
        if (recipe == thisRecipe)
        {
            event.cancel();
            var facings = 
            [
                IFacing.north(),
                IFacing.east(),
                IFacing.south(),
                IFacing.west(),
                IFacing.down(),
                IFacing.up()
            ] as IFacing[];

            for facing in facings
            {
                var neighborPos = event.position.getOffset(facing, 1);
                if (event.world.getBlockState(neighborPos).block.definition.id == <item:minecraft:gold_block>.asBlock().definition.id)
                    event.world.setBlockState(<blockstate:minecraft:diamond_block>, neighborPos);
            }
        }
    }

}, EventPriority.highest(), true);
```

it should be helpful

**Comment by Krutoy242** [comment]
Looks good!

**Comment by tttsaurus** [comment]
then ill not consider the second feature.

todos:
1. mobs in fluid
2. `ComplexOutput` mentioned in another issue

is it ok for you?

**Comment by Krutoy242** [comment]
Its ok!

**Comment by tttsaurus** [comment]
emm i just realized that i can add the second feature into `ComplexOutput`

but im currently refactoring so many things and nowhere near finishing

**Comment by tttsaurus** [comment]
[v1.4.0-preview-2](https://github.com/tttsaurus/Fluid-Interaction-Tweaker/releases/tag/v1.4.0-preview-2) has the features you requested
but entity conversion jei compat is still in the todo list

and no docs yet, have a look at [FBTweaker](https://github.com/tttsaurus/Fluid-Interaction-Tweaker/blob/main/src/main/java/com/tttsaurus/fluidintetweaker/wrapper/crt/impl/FBTweaker.java) for crt methods

**Comment by Krutoy242** [comment]
Thank you for info! I will try to utilize new functionality soon!

Could you write simplest example of CT script to add liquid interaction to start with?

**Comment by tttsaurus** [comment]
check out the release page, i attached an example. for other specific functionalities, please refer to the code

**Comment by tttsaurus** [comment]
fluid behavior (including entity conversion) jei compat done (v1.4.0)
