### ISSUE TITLE
[Feature Request] New API - use CraftTweaker types instead of plain strings

### ISSUE THREAD

**Issue by Krutoy242** [tttsaurus/Fluid-Interaction-Tweaker#6]
Please, in functions like `createSpawnEntityEvent(String id)`, use default type `IEntityDefinition` of CraftTweaker instead of a string.

Pros:
- Allow to use Bracket Captures inside code, that have better highlighting in VSCode and extensions.
- Properly handle "cant found entry" CT errors, for example when entity is from removed mod.

Also, `addCondition(String className, Object[] params)` could use ENUM instead of `String className`. This would be double-handy since ZS allow to use enum members without pointer. For example `addCondition(chance, [])` instead of `addCondition(enum.chance, [])`

**Comment by tttsaurus** [comment]
ill put it in the v1.5.0

**Comment by tttsaurus** [comment]
> since ZS allow to use enum members without pointer

then what about naming conflicts
im a bit confused how crt handles that

**Comment by Krutoy242** [comment]
Conflicts can happens but they are rare. This is my commit that show how this feature works: https://github.com/Krutoy242/Enigmatica2Expert-Extended/commit/0d5f5f99dbfe42da27971a42af6b2543782d47e1

But, its not that necessary. I just think that using enums is more convenient than predefined text words.

**Comment by tttsaurus** [comment]
commit `68bfbf1` i just made it into an enum wrapper

![image](https://github.com/user-attachments/assets/94eccd51-6d78-4da1-9359-5963b316b575)
you can see all the options if you have probezs and zs intellisense (vs code plugin) installed

btw in case you want to use the latest action build, dont use `.done()` anymore for both output builder and event builder

**Comment by Krutoy242** [comment]
> dont use .done() anymore for both output builder and event builder

Oh, than you! This `.done()` tails looked redundant.
