### ISSUE TITLE
Random Crash: Exception ticking world

### ISSUE THREAD

**Issue by Dan4oby** [tttsaurus/Fluid-Interaction-Tweaker#7]
I use last version of the mod and Cleanroom Loader. Also i have no configs for mod beside defaults

[crash-2024-11-02_20.17.52-server.txt](https://github.com/user-attachments/files/17607782/crash-2024-11-02_20.17.52-server.txt)

**Comment by tttsaurus** [comment]
can you also show your script

**Comment by tttsaurus** [comment]
please download the latest one from the github action and try so i can know whether my fix works

**Comment by tttsaurus** [comment]
i believe it should be fixed in v1.5.0
