### ISSUE TITLE
FIT breaking ExNihilo fluid interactions

### ISSUE THREAD

**Issue by Krutoy242** [tttsaurus/Fluid-Interaction-Tweaker#9]
This how it _should_ be: `witch water` + `lava` = stone variants (granite, diorite, andesite)
![javaw_Bcs54pl78Z](https://github.com/user-attachments/assets/217d2c9e-81f6-48ed-a4d3-bd33c99407ac)

With FIT installed, it produce **only** cobblestone.

**Comment by tttsaurus** [comment]
did you add related FIT recipes that may override exnihilo's witch water recipes?

**Comment by Krutoy242** [comment]
No. I only changed Lava + Modded, Water + Modded, Modded + Modded interactions. And no of those interactions includes Witchwater.

**Comment by tttsaurus** [comment]
![Snipaste_2024-12-06_13-21-01](https://github.com/user-attachments/assets/6b4b82a5-e17f-486f-8e45-389e8dbf57aa)
![Snipaste_2024-12-06_13-21-12](https://github.com/user-attachments/assets/8192da20-ef6c-442d-bf8b-8959c08fc530)

i also added an unrelated lava recipe to test but witch water worked fine

[testbranch.zip](https://github.com/user-attachments/files/18042191/testbranch.zip)

nevertheless, i did some minor changes, pls try

**Comment by tttsaurus** [comment]
how was the test branch?

**Comment by Krutoy242** [comment]
Didnt test yet.
Also, further test on normal version shows that cobblestone generated only when Lava advance towards Witchwater, but working fine when opposite.

**Comment by Krutoy242** [comment]
I tested and yes, now everything working fine.
